--- 
title: 'Data From: TERRA-REF, An Open Reference Data Set From High Resolution Genomics,
  Phenomics, and Imaging Sensors'
author:
 - David LeBauer^[University of Arizona, orcid:0000-0001-7228-053X]
 - Maxwell A. Burnette^[NCSA, University of Illinois at Urbana-Champaign, orcid:0000-0002-1786-3676]
 - Jeffrey Demieville^[University of Arizona, orcid:0000-0002-7725-7379]
 - Noah Fahlgren^[Donald Danforth Plant Science Center, orcid:0000-0002-5597-4537]
 - Andrew N. French^[USDA Agricultural Research Service, orcid:0000-0002-4018-1817]
 - Roman Garnett^[Washington University in St. Louis, orcid:0000-0002-0152-5453]
 - Zhenbin Hu^[Kansas State University, orcid:0000-0002-1500-1255]
 - Kimberly Huynh^[University of Arizona, orcid:0000-0003-3360-4073]
 - Rob Kooper^[NCSA, University of Illinois at Urbana-Champaign, orcid:0000-0002-5781-7287]
 - Zongyang Li^[Donald Danforth Plant Science Center, orcid:0000-0002-8601-378X]
 - Maitiniyazi Maimaitijiang^[Saint Louis University, orcid:0000-0001-6153-1583]
 - Jerome Mao^[University of California at Irvine, current: Case Western Reserve University orcid:0000-0003-2505-8666]
 - Todd C. Mockler^[Donald Danforth Plant Science Center, orcid:0000-0002-0462-5775]
 - Geoffrey Morris^[Kansas State University, orcid:0000-0002-3067-3359]
 - Maria Newcomb^[University of Arizona, current: USDA Forest Service, orcid:0000-0003-2974-9149]
 - Michael J Ottman^[University of Arizona, orcid:0000-0003-0763-3073]
 - Philip Ozersky^[Danforth Plant Science Center, orcid:0000-0002-8942-0524]
 - Sidike Paheding^[Saint Louis University, orcid:0000-0003-4712-9672]
 - Duke Pauli^[University of Arizona, orcid:0000-0002-8292-2388]
 - Robert Pless^[George Washington University, orcid:0000-0001-5775-8216]
 - Wei Qin^[University of Illinois at Urbana-Champaign, current: Amazon.com, Inc]
 - Kristina Riemer^[University of Arizona, orcid:0000-0003-3802-3331]
 - Gareth Scott Rohde^[University of Illinois at Urbana-Champaign, orcid:0000-0001-9030-0936]
 - William L. Rooney^[Texas A&M University, orcid:0000-0001-7953-1856]
 - Vasit Sagan^[Saint Louis University, orcid:0000-0003-4375-2096]
 - Nadia Shakoor^[Donald Danforth Plant Science Center, orcid:0000-0002-2035-7117]
 - Abby Stylianou^[Saint Louis University, orcid:0000-0002-4387-028X]
 - Kelly Thorp^[USDA Agricultural Research Service, orcid:0000-0001-9168-875X]
 - Richard Ward^[University of Arizona, current:unaffiliated , orcid:0000-0003-4436-0019]
 - Jeffrey W White^[USDA Agricultural Research Service, current: University of Florida, orcid:0000-0002-2051-4645]
 - Craig Willis^[University of Illinois at Urbana-Champaign, orcid:0000-0002-6148-7196]
 - Charles S Zender^[University of California, Irvine, orcid:0000-0003-0129-8024]
date: "`r Sys.Date()`"
bibliography:
- book.bib
- packages.bib
description: This describes the TERRA REF public data release
documentclass: book
geometry: margin=1in
link-citations: yes
site: bookdown::bookdown_site
biblio-style: apalike
urlcolor: blue
linkcolor: blue
---

```{r include = FALSE}

knitr::opts_chunk$set(
  echo = FALSE,
  include = FALSE,
  cache = TRUE, 
  message = FALSE)#,
  #root.dir = normalizePath("../book")))

library(dplyr)
library(stringr)
library(ggplot2)

#Setting up traits package
#library(traits)
#options(betydb_url = "https://terraref.ncsa.illinois.edu/bety/",
#        betydb_api_version = 'v1',
#        betydb_key = readLines('~/.betykey', warn = FALSE))

# to query the database either use 
# ssh -Nf -L 5432:localhost:5432 bety6.ncsa.illinois.edu 
# to mount the database
try(
bety_src <- src_postgres(dbname = "bety",
                         password = 'DelchevskoOro',
                         host = 'localhost',
                         user = 'viewer',
                         port = 5432)
, silent = TRUE)
# for use with publication: after making data public 
# cd code/betydb_docker
# docker-compose up -d postgres
# docker-compose run --rm bety initialize
# docker-compose run --rm bety sync
# bety_src <- src_postgres(dbname = "bety", 
#                          password = 'bety',
#                          host = 'localhost', 
#                          user = 'bety',
#                          port = 5433)
```


```{r include=FALSE}
# automatically create a bib database for R packages
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown'
), 'packages.bib')
```

