# Abstract

The ARPA-E funded TERRA REF project is generating open access reference datasets for the study of plant sensing, genomics, and phenomics. Sensor data are generated by a field scanner sensing platform that captures color, thermal, hyperspectral, and active flourescence imagery as well as three dimensional structure and associated environmental measurements. These data are provided alongside traditional field methods to support calibration and validation of algorithms used to extract plot level phenotypes from these datasets.

Data were collected at a field site in Maricopa, AZ that hosts a large field scanner with fifteen sensors, many of which are capable of capturing mm-scale images and point clouds at daily to weekly intervals.

These data are intended to be reused, and are accessible as a combination of files and databases linked by spatial, temporal, and genomic information. In addition to providing open access data, the entire computational pipeline is open source, and we enable users to access high-performance computing environments.

The study has evaluated a sorghum diversity panel, biparental cross populations, and elite lines and hybrids from structured breeding populations as well as a durum wheat diversity panel. The TERRA REF reference dataset can be used to characterize phenotype-to-genotype associations, on a genomic scale, that will enable knowledge-driven breeding and the development of higher-yielding cultivars of sorghum and wheat. The data is also being used to develop new algorithms for machine learning, image analysis, genomics, and optical sensor engineering.
