#docker-compose -p bety up  -d postgres
#
# initialize BETY database
#docker run -ti --rm --network bety_bety -e BETY_INITIALIZE_URL='-w https://terraref.ncsa.illinois.edu/bety/dump/bety0/bety.tar.gz' pecan/bety:develop initialize
#
# sync  BETY database
#docker run -ti --rm --network bety_bety -e REMOTE_SERVERS=6  pecan/bety:terra sync
#
# run brapi:
# docker-compose -p bety up brapi

version: "3"

services:
  # postgresql + postgis to hold all the data
  postgres:
    image: mdillon/postgis:9.5
    networks:
      - bety
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 5433:5432
    restart: unless-stopped

  # BETY rails frontend to the database
  bety:
    image: pecan/bety:${BRANCH:-latest}
    networks:
      - bety
    ports:
      - 8000:8000
    environment:
      - INITIALIZE_URL=-w https://terraref.ncsa.illinois.edu/bety/dump/bety0/bety.tar.gz
      - REMOTE_SERVERS=6
      - UNICORN_WORKER_PROCESSES=1
      - SECRET_KEY_BASE=thisissomereallllllylongsecretkeyandshouldbelongerthanthis
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  bety:

volumes:
  postgres:
